name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Running Cypress Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: install
      run: npm install
    - name: start server
      run: npm start & wait-on http://localhost:3000
    - name: test
      run: npm run cypress
